(()=>{"use strict";
const KEY="olen.chat.conversations.v1",ACTIVE="olen.chat.active.v1";
const one=s=>document.querySelector(s),all=s=>Array.from(document.querySelectorAll(s));
const el={chat:one("#olenChat"),side:one("#olenChatSidebar"),scrim:one("#olenChatScrim"),messages:one("#olenChatMessages"),sections:one("#olenSideSections"),input:one("#olenChatInput"),action:one("#olenChatAction"),search:one("#olenChatSearchPop"),searchInput:one("#olenSearchInput"),results:one("#olenSearchResults"),more:one("#olenChatMore"),longMenu:one("#olenLongMenu"),longScrim:one("#olenLongScrim")};let selected=null,generating=false;
const demo=()=>({id:"demo-sintra-scroll-v1",title:"Fim de semana em Sintra",pinned:true,updated:Date.now(),messages:[{role:"user",text:"Quero preparar um fim de semana em Sintra."},{role:"assistant",text:"Claro. Posso organizar uma proposta equilibrada entre património, natureza e tempo livre."},{role:"user",text:"Prefiro evitar um plano demasiado apertado."},{role:"assistant",text:"Perfeito. Deixo margem entre experiências e concentro o essencial sem transformar o passeio numa corrida."}]});
const load=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");if(Array.isArray(v)&&v.length)return v}catch{}const v=[demo()];save(v);return v},save=v=>localStorage.setItem(KEY,JSON.stringify(v));
const current=()=>{const v=load(),id=localStorage.getItem(ACTIVE);return v.find(x=>x.id===id)||v[0]},safe=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function actionBar(){return '<div class="msg-actions"><button data-msg="copy">⧉</button><button data-msg="up">♡</button><button data-msg="down">♧</button><button data-msg="share">↗</button><button data-msg="retry">↻</button><button data-msg="more">⋯</button></div>'}
function drawMessages(){const c=current();el.messages.innerHTML=c.messages.map(m=>m.role==="user"?'<div class="bubble me">'+safe(m.text)+'</div>':'<div class="assistant"><div class="bubble">'+safe(m.text)+'</div>'+actionBar()+'</div>').join("")+(c.messages.length>=15?'<div class="useful">Esta conversa foi útil até agora?<div class="useful-actions"><button>♡</button><button>♧</button><button>×</button></div></div>':"");el.messages.scrollTop=el.messages.scrollHeight}
function group(title,v,more){if(!v.length)return "";return '<section class="section"><div class="section-title">'+title+'</div>'+v.map(c=>'<div class="conv-row"><button class="conv" data-conv="'+c.id+'">'+safe(c.title)+'</button><button class="conv-more" data-options="'+c.id+'" aria-label="Opções">⋮</button></div>').join("")+(more?'<button class="side-more">Ver todas</button>':"")+'</section>'}
function drawSidebar(){const v=load().sort((a,b)=>(b.updated||0)-(a.updated||0)),p=v.filter(x=>x.pinned).slice(0,10),r=v.filter(x=>!x.pinned);el.sections.innerHTML=group("Afixados",p,false)+group("Recentes",r.slice(0,5),r.length>5);bindRows()}
function draw(){drawMessages();drawSidebar();syncAction()}
function openSide(){el.side.classList.add("open");el.chat.classList.add("side-open");el.side.setAttribute("aria-hidden","false");el.scrim.style.cssText="opacity:1;visibility:visible"}
function closeSide(){el.side.classList.remove("open");el.chat.classList.remove("side-open");el.side.setAttribute("aria-hidden","true");el.scrim.style.cssText=""}
function activate(id){localStorage.setItem(ACTIVE,id);draw();closeSide()}
function createChat(){const v=load(),id="chat-"+Date.now();v.unshift({id,title:"Nova conversa",pinned:false,updated:Date.now(),messages:[]});save(v);localStorage.setItem(ACTIVE,id);draw();closeSide();el.input.focus()}
function showLong(id){selected=id;el.longMenu.hidden=false;el.longScrim.hidden=false;el.longScrim.style.cssText="opacity:1;visibility:visible"}
function hideLong(){selected=null;el.longMenu.hidden=true;el.longScrim.hidden=true;el.longScrim.style.cssText=""}
function bindRows(){all("[data-conv]").forEach(b=>{let timer=null,x=0,y=0,opened=false;const cancel=()=>{if(timer){clearTimeout(timer);timer=null}};b.onpointerdown=e=>{if(e.pointerType==="mouse")return;x=e.clientX;y=e.clientY;opened=false;cancel();timer=setTimeout(()=>{timer=null;opened=true;showLong(b.dataset.conv)},500)};b.onpointermove=e=>{if(Math.abs(e.clientX-x)>12||Math.abs(e.clientY-y)>12)cancel()};b.onpointerup=cancel;b.onpointercancel=cancel;b.onclick=e=>{if(opened){opened=false;e.preventDefault();return}activate(b.dataset.conv)};b.oncontextmenu=e=>{if(matchMedia("(pointer:coarse)").matches){e.preventDefault();cancel();showLong(b.dataset.conv)}}});all("[data-options]").forEach(b=>b.onclick=e=>{e.stopPropagation();showLong(b.dataset.options)})}
function openSearch(){el.search.hidden=false;el.searchInput.value="";search();setTimeout(()=>el.searchInput.focus())}function search(){const q=el.searchInput.value.trim().toLowerCase(),v=load().filter(c=>!q||c.title.toLowerCase().includes(q)||c.messages.some(m=>(m.text||"").toLowerCase().includes(q)));el.results.innerHTML=v.length?v.map(c=>'<button class="result" data-result="'+c.id+'"><b>'+safe(c.title)+'</b></button>').join(""):'<div class="hint">Sem resultados.</div>'}
function resize(){el.input.style.height="auto";el.input.style.height=Math.min(el.input.scrollHeight,112)+"px"}function syncAction(){const mode=generating?"stop":el.input.value.trim()?"send":"voice";el.action.dataset.mode=mode;el.action.setAttribute("aria-label",mode==="send"?"Enviar mensagem":mode==="stop"?"Parar":"Iniciar voz")}
function send(){const text=el.input.value.trim();if(!text)return;const v=load(),c=v.find(x=>x.id===current().id);c.messages.push({role:"user",text});if(c.title==="Nova conversa")c.title=text.slice(0,42);c.updated=Date.now();save(v);el.input.value="";resize();draw()}
one("#olenChatMenuBtn").onclick=()=>el.side.classList.contains("open")?closeSide():openSide();one("#olenRailToggle").onclick=openSide;one("#olenSideCollapse").onclick=closeSide;el.scrim.onclick=closeSide;one("#olenNewChatBtn").onclick=createChat;one("#olenSideNew").onclick=createChat;one("#olenChatSearchBtn").onclick=openSearch;one("#olenSearchBack").onclick=()=>el.search.hidden=true;el.searchInput.oninput=search;el.results.onclick=e=>{const b=e.target.closest("[data-result]");if(b){el.search.hidden=true;activate(b.dataset.result)}};el.input.oninput=()=>{resize();syncAction()};el.input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};el.action.onclick=()=>{if(el.action.dataset.mode==="send")send()};one("#olenChatMoreBtn").onclick=e=>{e.stopPropagation();el.more.hidden=!el.more.hidden};el.longScrim.onclick=hideLong;
el.longMenu.onclick=e=>{const b=e.target.closest("[data-long]");if(!b||!selected)return;const v=load(),c=v.find(x=>x.id===selected);if(!c)return;if(b.dataset.long==="pin")c.pinned=!c.pinned;if(b.dataset.long==="rename"){const n=prompt("Novo nome",c.title);if(n&&n.trim())c.title=n.trim()}if(b.dataset.long==="delete"){v.splice(v.indexOf(c),1);if(!v.length)v.push(demo());localStorage.setItem(ACTIVE,v[0].id)}save(v);hideLong();draw()};document.addEventListener("click",e=>{if(!e.target.closest("#olenChatMoreBtn")&&!e.target.closest("#olenChatMore"))el.more.hidden=true});if(!localStorage.getItem(ACTIVE))localStorage.setItem(ACTIVE,load()[0].id);draw();window.OLENChatV4={openSidebar:openSide,closeSidebar:closeSide,newConversation:createChat,render:draw};
})();